Repository xbmc/repo-scripts, pull requests merged in 2020-03, with the labels that each got.

#1251 [script.module.tmdbsimple] 2.2.0
  script.module.tmdbsimple/LICENSE.txt
  script.module.tmdbsimple/README.md
  script.module.tmdbsimple/addon.xml
  script.module.tmdbsimple/lib/LICENSE
  script.module.tmdbsimple/lib/README.rst
  script.module.tmdbsimple/lib/tmdbsimple/__init__.py
  script.module.tmdbsimple/lib/tmdbsimple/account.py
  script.module.tmdbsimple/lib/tmdbsimple/base.py
  script.module.tmdbsimple/lib/tmdbsimple/changes.py
  script.module.tmdbsimple/lib/tmdbsimple/configuration.py
  script.module.tmdbsimple/lib/tmdbsimple/discover.py
  script.module.tmdbsimple/lib/tmdbsimple/find.py
  script.module.tmdbsimple/lib/tmdbsimple/genres.py
  script.module.tmdbsimple/lib/tmdbsimple/movies.py
  script.module.tmdbsimple/lib/tmdbsimple/people.py
  script.module.tmdbsimple/lib/tmdbsimple/search.py
  script.module.tmdbsimple/lib/tmdbsimple/tv.py
  script.module.tmdbsimple/resources/icon.png
Labels: No addon is using it

#1306 [script.module.simplecache] 2.0.0
  script.module.simplecache/LICENSE
  script.module.simplecache/README.md
  script.module.simplecache/addon.xml
  script.module.simplecache/lib/simplecache.py
  script.module.simplecache/resources/icon.png
Labels: Python3

#1328 [script.skin.helper.colorpicker] 2.0.0
  script.skin.helper.colorpicker/LICENSE.txt
  script.skin.helper.colorpicker/README.md
  script.skin.helper.colorpicker/addon.xml
  script.skin.helper.colorpicker/default.py
  script.skin.helper.colorpicker/resources/__init__.py
  script.skin.helper.colorpicker/resources/colors/colors.xml
  script.skin.helper.colorpicker/resources/fanart.jpg
  script.skin.helper.colorpicker/resources/icon.png
  script.skin.helper.colorpicker/resources/language/resource.language.en_gb/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.es_es/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.fr_fr/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.he_IL/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.it_it/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.nl_nl/strings.po
  script.skin.helper.colorpicker/resources/language/resource.language.sk_sk/strings.po
  script.skin.helper.colorpicker/resources/lib/ColorPicker.py
  script.skin.helper.colorpicker/resources/lib/__init__.py
  script.skin.helper.colorpicker/resources/skins/Default/1080i/script-skin_helper_service-ColorPicker.xml
  script.skin.helper.colorpicker/resources/skins/Default/media/bgpanel.png
  script.skin.helper.colorpicker/resources/skins/Default/media/inner.png
  script.skin.helper.colorpicker/resources/skins/Default/media/panel.png
  script.skin.helper.colorpicker/resources/skins/Default/media/panel_trans.png
  script.skin.helper.colorpicker/resources/skins/Default/media/poster.png
  script.skin.helper.colorpicker/resources/skins/Default/media/separator.png
  script.skin.helper.colorpicker/resources/skins/Default/media/slider/slider_back.png
  script.skin.helper.colorpicker/resources/skins/Default/media/slider/slider_button_focus.png
  script.skin.helper.colorpicker/resources/skins/Default/media/slider/slider_button_new.png
  script.skin.helper.colorpicker/resources/skins/Default/media/slider/slider_button_nofocus.png
Labels: Python3

#1327 [script.metadata.editor] 3.0.0
  script.metadata.editor/README.md
  script.metadata.editor/addon.xml
  script.metadata.editor/context.py
  script.metadata.editor/default.py
  script.metadata.editor/resources/__init__.py
  script.metadata.editor/resources/fanart.jpg
  script.metadata.editor/resources/icon.png
  script.metadata.editor/resources/language/resource.language.de_DE/strings.po
  script.metadata.editor/resources/language/resource.language.en_GB/strings.po
  script.metadata.editor/resources/language/resource.language.es_ES/strings.po
  script.metadata.editor/resources/language/resource.language.it_IT/strings.po
  script.metadata.editor/resources/language/resource.language.nl_NL/strings.po
  script.metadata.editor/resources/language/resource.language.pt_BR/strings.po
  script.metadata.editor/resources/language/resource.language.ru_RU/strings.po
  script.metadata.editor/resources/language/resource.language.tr_TR/strings.po
  script.metadata.editor/resources/lib/__init__.py
  script.metadata.editor/resources/lib/database.py
  script.metadata.editor/resources/lib/editor.py
  script.metadata.editor/resources/lib/functions.py
  script.metadata.editor/resources/lib/helper.py
  script.metadata.editor/resources/lib/json_map.py
  script.metadata.editor/resources/lib/nfo_updater.py
  script.metadata.editor/resources/lib/rating_updater.py
  script.metadata.editor/resources/media/icon_array.png
  script.metadata.editor/resources/media/icon_date.png
  script.metadata.editor/resources/media/icon_float.png
  script.metadata.editor/resources/media/icon_integer.png
  script.metadata.editor/resources/media/icon_string.png
  script.metadata.editor/resources/settings.xml
  script.metadata.editor/service.py
Labels: Python3

#1324 [script.toolbox] 2.0.0
  script.toolbox/LICENSE.txt
  script.toolbox/Readme.md
  script.toolbox/addon.xml
  script.toolbox/default.py
  script.toolbox/resources/__init__.py
  script.toolbox/resources/icon.png
  script.toolbox/resources/language/resource.language.en_GB/strings.po
  script.toolbox/resources/lib/ImageOperations.py
  script.toolbox/resources/lib/Utils.py
  script.toolbox/resources/lib/__init__.py
Labels: Python3

#1332 [script.module.autocompletion] 2.0.0
  script.module.autocompletion/LICENSE.txt
  script.module.autocompletion/__init__.py
  script.module.autocompletion/addon.xml
  script.module.autocompletion/lib/AutoCompletion.py
  script.module.autocompletion/lib/__init__.py
  script.module.autocompletion/resources/data/common_de.txt
  script.module.autocompletion/resources/data/common_en.txt
  script.module.autocompletion/resources/data/common_fr.txt
  script.module.autocompletion/resources/data/common_nl.txt
  script.module.autocompletion/resources/icon.png
Labels: Python3

#1333 [plugin.program.autocompletion] 2.0.0
  plugin.program.autocompletion/LICENSE.txt
  plugin.program.autocompletion/addon.xml
  plugin.program.autocompletion/changelog.txt
  plugin.program.autocompletion/default.py
  plugin.program.autocompletion/plugin.py
  plugin.program.autocompletion/resources/icon.png
  plugin.program.autocompletion/resources/language/resource.language.en_GB/strings.po
  plugin.program.autocompletion/resources/language/resource.language.he_IL/strings.po
  plugin.program.autocompletion/resources/language/resource.language.it_IT/strings.po
  plugin.program.autocompletion/resources/screenshot-01.jpg
  plugin.program.autocompletion/resources/screenshot-02.jpg
  plugin.program.autocompletion/resources/screenshot-03.jpg
  plugin.program.autocompletion/resources/settings.xml
Labels: Python3

#1329 [script.embuary.helper] 2.0.0
  script.embuary.helper/README.md
  script.embuary.helper/addon.xml
  script.embuary.helper/default.py
  script.embuary.helper/plugin.py
  script.embuary.helper/resources/__init__.py
  script.embuary.helper/resources/fanart.jpg
  script.embuary.helper/resources/icon.png
  script.embuary.helper/resources/language/resource.language.de_DE/strings.po
  script.embuary.helper/resources/language/resource.language.en_GB/strings.po
  script.embuary.helper/resources/language/resource.language.es_ES/strings.po
  script.embuary.helper/resources/language/resource.language.it_IT/strings.po
  script.embuary.helper/resources/language/resource.language.nl_NL/strings.po
  script.embuary.helper/resources/language/resource.language.pl_PL/strings.po
  script.embuary.helper/resources/language/resource.language.pt_BR/strings.po
  script.embuary.helper/resources/language/resource.language.pt_PT/strings.po
  script.embuary.helper/resources/language/resource.language.ru_RU/strings.po
  script.embuary.helper/resources/language/resource.language.sk_SK/strings.po
  script.embuary.helper/resources/language/resource.language.tr_TR/strings.po
  script.embuary.helper/resources/language/resource.language.zh_CN/strings.po
  script.embuary.helper/resources/lib/__init__.py
  script.embuary.helper/resources/lib/cinema_mode.py
  script.embuary.helper/resources/lib/helper.py
  script.embuary.helper/resources/lib/image.py
  script.embuary.helper/resources/lib/json_map.py
  script.embuary.helper/resources/lib/library.py
  script.embuary.helper/resources/lib/player_monitor.py
  script.embuary.helper/resources/lib/plugin_actions.py
  script.embuary.helper/resources/lib/plugin_content.py
  script.embuary.helper/resources/lib/plugin_listing.py
  script.embuary.helper/resources/lib/service_monitor.py
  script.embuary.helper/resources/lib/utils.py
  script.embuary.helper/resources/settings.xml
  script.embuary.helper/resources/trailer.jpg
  script.embuary.helper/service.py
Labels: Python3

#1322 [script.module.kodi-six] 0.1.3
  script.module.kodi-six/LICENSE.txt
  script.module.kodi-six/addon.xml
  script.module.kodi-six/icon.png
  script.module.kodi-six/libs/kodi_six/__init__.py
  script.module.kodi-six/libs/kodi_six/utils.py
  script.module.kodi-six/libs/kodi_six/xbmc.py
  script.module.kodi-six/libs/kodi_six/xbmcaddon.py
  script.module.kodi-six/libs/kodi_six/xbmcdrm.py
  script.module.kodi-six/libs/kodi_six/xbmcgui.py
  script.module.kodi-six/libs/kodi_six/xbmcplugin.py
  script.module.kodi-six/libs/kodi_six/xbmcvfs.py
Labels: Don't Merge, Python3

#1346 [service.subtitles.opensubtitles] 5.1.0
  service.subtitles.opensubtitles/README.md
  service.subtitles.opensubtitles/addon.xml
  service.subtitles.opensubtitles/changelog.txt
  service.subtitles.opensubtitles/icon.png
  service.subtitles.opensubtitles/logo.png
  service.subtitles.opensubtitles/resources/language/resource.language.en_GB/strings.po
  service.subtitles.opensubtitles/resources/language/resource.language.zh_CN/strings.po
  service.subtitles.opensubtitles/resources/lib/OSUtilities.py
  service.subtitles.opensubtitles/resources/lib/__init__.py
  service.subtitles.opensubtitles/resources/media/os_fanart.jpg
  service.subtitles.opensubtitles/resources/media/os_logo_512x512.png
  service.subtitles.opensubtitles/resources/media/screenshot_1.jpg
  service.subtitles.opensubtitles/resources/media/screenshot_2.jpg
  service.subtitles.opensubtitles/resources/media/screenshot_3.jpg
  service.subtitles.opensubtitles/resources/settings.xml
  service.subtitles.opensubtitles/service.py
Labels: waiting for developer to respond

#1349 [script.module.routing] 0.2.3+matrix
  script.module.routing/LICENSE.txt
  script.module.routing/README.md
  script.module.routing/addon.xml
  script.module.routing/lib/routing.py
  script.module.routing/lib/tests.py
  script.module.routing/resources/icon.png
Labels: Python3

#1186 [service.library.data.provider] v0.4.0
  service.library.data.provider/LICENSE
  service.library.data.provider/README.md
  service.library.data.provider/addon.xml
  service.library.data.provider/plugin.py
  service.library.data.provider/resources/__init__.py
  service.library.data.provider/resources/fanart.jpg
  service.library.data.provider/resources/icon.png
  service.library.data.provider/resources/language/resource.language.en_gb/strings.po
  service.library.data.provider/resources/language/resource.language.fr_fr/strings.po
  service.library.data.provider/resources/language/resource.language.he_il/strings.po
  service.library.data.provider/resources/language/resource.language.it_it/strings.po
  service.library.data.provider/resources/language/resource.language.pl_pl/strings.po
  service.library.data.provider/resources/lib/__init__.py
  service.library.data.provider/resources/lib/data.py
  service.library.data.provider/resources/lib/library.py
  service.library.data.provider/resources/lib/router.py
  service.library.data.provider/resources/settings.xml
  service.library.data.provider/service.py
Labels: waiting for developer to respond

#1307 [script.embuary.info] 2.0.1
  script.embuary.info/README.md
  script.embuary.info/addon.xml
  script.embuary.info/default.py
  script.embuary.info/plugin.py
  script.embuary.info/resources/__init__.py
  script.embuary.info/resources/fanart.jpg
  script.embuary.info/resources/icon.png
  script.embuary.info/resources/language/resource.language.de_DE/strings.po
  script.embuary.info/resources/language/resource.language.en_GB/strings.po
  script.embuary.info/resources/language/resource.language.es_ES/strings.po
  script.embuary.info/resources/language/resource.language.hu_HU/strings.po
  script.embuary.info/resources/language/resource.language.it_IT/strings.po
  script.embuary.info/resources/language/resource.language.nl_NL/strings.po
  script.embuary.info/resources/language/resource.language.pt_BR/strings.po
  script.embuary.info/resources/language/resource.language.pt_PT/strings.po
  script.embuary.info/resources/language/resource.language.ru_RU/strings.po
  script.embuary.info/resources/language/resource.language.sk_SK/strings.po
  script.embuary.info/resources/language/resource.language.zh_CN/strings.po
  script.embuary.info/resources/lib/__init__.py
  script.embuary.info/resources/lib/helper.py
  script.embuary.info/resources/lib/localdb.py
  script.embuary.info/resources/lib/main.py
  script.embuary.info/resources/lib/nextaired.py
  script.embuary.info/resources/lib/omdb.py
  script.embuary.info/resources/lib/person.py
  script.embuary.info/resources/lib/season.py
  script.embuary.info/resources/lib/tmdb.py
  script.embuary.info/resources/lib/trakt.py
  script.embuary.info/resources/lib/tvdb.py
  script.embuary.info/resources/lib/video.py
  script.embuary.info/resources/lib/widgets.py
  script.embuary.info/resources/settings.xml
  script.embuary.info/resources/skins/default/1080i/script-embuary-image.xml
  script.embuary.info/resources/skins/default/1080i/script-embuary-person.xml
  script.embuary.info/resources/skins/default/1080i/script-embuary-video.xml
  script.embuary.info/resources/skins/default/media/DefaultActor.png
  script.embuary.info/resources/skins/default/media/DefaultPicture.png
  script.embuary.info/resources/skins/default/media/DefaultVideo.png
  script.embuary.info/resources/skins/default/media/backgrounds/primary.jpg
  script.embuary.info/resources/skins/default/media/colors/black.png
  script.embuary.info/resources/skins/default/media/colors/grey.png
  script.embuary.info/resources/skins/default/media/colors/white.png
  script.embuary.info/resources/skins/default/media/colors/white50.png
  script.embuary.info/resources/skins/default/media/colors/white70.png
  script.embuary.info/resources/skins/default/media/dialogs/dialog-bg.png
  script.embuary.info/resources/skins/default/media/frame/InfoBar.png
  script.embuary.info/resources/skins/default/media/icons/OverlayLocal.png
  script.embuary.info/resources/skins/default/media/icons/OverlayWatched.png
  script.embuary.info/resources/skins/default/media/icons/browse.png
  script.embuary.info/resources/skins/default/media/icons/disable.png
  script.embuary.info/resources/skins/default/media/icons/play.png
  script.embuary.info/resources/skins/default/media/icons/plot.png
  script.embuary.info/resources/skins/default/media/list/focus.png
  script.embuary.info/resources/skins/default/media/overlays/overlay-bg.png
  script.embuary.info/resources/skins/default/media/overlays/shadow.png
  script.embuary.info/resources/skins/default/media/tmdb.png
  script.embuary.info/service.py
Labels: Python3

#1339 [context.embuary.info] 2.0.0
  context.embuary.info/README.md
  context.embuary.info/addon.py
  context.embuary.info/addon.xml
  context.embuary.info/resources/__init__.py
  context.embuary.info/resources/fanart.jpg
  context.embuary.info/resources/icon.png
  context.embuary.info/resources/language/resource.language.en_gb/strings.po
Labels: Python3, waiting for dependency to be reviewed

#1355 [script.module.inputstreamhelper] 0.4.4+matrix.1
  script.module.inputstreamhelper/LICENSE.txt
  script.module.inputstreamhelper/README.md
  script.module.inputstreamhelper/addon.xml
  script.module.inputstreamhelper/default.py
  script.module.inputstreamhelper/lib/__init__.py
  script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py
  script.module.inputstreamhelper/lib/inputstreamhelper/api.py
  script.module.inputstreamhelper/lib/inputstreamhelper/config.py
  script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py
  script.module.inputstreamhelper/lib/inputstreamhelper/utils.py
  script.module.inputstreamhelper/resources/icon.png
  script.module.inputstreamhelper/resources/language/resource.language.de_de/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.el_gr/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.fr_fr/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.hr_hr/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.hu_hu/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.it_it/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.ja_JP/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.ko_KR/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.nl_nl/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.ru_ru/strings.po
  script.module.inputstreamhelper/resources/language/resource.language.sv_se/strings.po
  script.module.inputstreamhelper/resources/settings.xml
Labels: Python3

#1342 [script.module.pyxbmct] 1.3.1+matrix
  script.module.pyxbmct/License.txt
  script.module.pyxbmct/addon.xml
  script.module.pyxbmct/icon.png
  script.module.pyxbmct/lib/pyxbmct/__init__.py
  script.module.pyxbmct/lib/pyxbmct/addonskin.py
  script.module.pyxbmct/lib/pyxbmct/addonwindow.py
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/AddonWindow/ContentPanel.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/AddonWindow/DialogCloseButton-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/AddonWindow/DialogCloseButton.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/AddonWindow/SKINDEFAULT.jpg
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/AddonWindow/dialogheader.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Button/KeyboardKey.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Button/KeyboardKeyNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Edit/black-back2.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Edit/button-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/List/MenuItemFO.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/List/MenuItemNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/RadioButton/MenuItemFO.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/RadioButton/MenuItemNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/RadioButton/radiobutton-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/RadioButton/radiobutton-nofocus.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Slider/osd_slider_bg.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Slider/osd_slider_nib.png
  script.module.pyxbmct/lib/pyxbmct/textures/confluence/Slider/osd_slider_nibNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/AddonWindow/ContentPanel.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/AddonWindow/DialogCloseButton-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/AddonWindow/DialogCloseButton.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/AddonWindow/SKINDEFAULT.jpg
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/AddonWindow/dialogheader.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Button/KeyboardKey.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Button/KeyboardKeyNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Edit/black-back2.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Edit/button-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/List/MenuItemFO.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/List/MenuItemNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/RadioButton/MenuItemFO.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/RadioButton/MenuItemNF.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/RadioButton/radiobutton-focus.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/RadioButton/radiobutton-nofocus.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Slider/osd_slider_bg.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Slider/osd_slider_nib.png
  script.module.pyxbmct/lib/pyxbmct/textures/estuary/Slider/osd_slider_nibNF.png
Labels: Python3

#1357 [service.subtitles.pipocas] 1.0.0
  service.subtitles.pipocas/README.md
  service.subtitles.pipocas/addon.xml
  service.subtitles.pipocas/changelog.txt
  service.subtitles.pipocas/icon.png
  service.subtitles.pipocas/resources/language/English/strings.po
  service.subtitles.pipocas/resources/language/English/strings.xml
  service.subtitles.pipocas/resources/language/Portuguese (Brazil)/strings.po
  service.subtitles.pipocas/resources/language/Portuguese (Brazil)/strings.xml
  service.subtitles.pipocas/resources/language/Portuguese/strings.po
  service.subtitles.pipocas/resources/language/Portuguese/strings.xml
  service.subtitles.pipocas/resources/lib/__init__.py
  service.subtitles.pipocas/resources/lib/pipocas.py
  service.subtitles.pipocas/resources/settings.xml
  service.subtitles.pipocas/service.py
Labels: waiting for developer to respond

#1362 [script.module.beautifulsoup4] 4.8.2+matrix.1
  script.module.beautifulsoup4/AUTHORS.txt
  script.module.beautifulsoup4/LICENSE
  script.module.beautifulsoup4/NEWS.txt
  script.module.beautifulsoup4/README.md
  script.module.beautifulsoup4/addon.xml
  script.module.beautifulsoup4/lib/bs4/__init__.py
  script.module.beautifulsoup4/lib/bs4/builder/__init__.py
  script.module.beautifulsoup4/lib/bs4/builder/_html5lib.py
  script.module.beautifulsoup4/lib/bs4/builder/_htmlparser.py
  script.module.beautifulsoup4/lib/bs4/builder/_lxml.py
  script.module.beautifulsoup4/lib/bs4/dammit.py
  script.module.beautifulsoup4/lib/bs4/diagnose.py
  script.module.beautifulsoup4/lib/bs4/element.py
  script.module.beautifulsoup4/lib/bs4/formatter.py
  script.module.beautifulsoup4/lib/bs4/testing.py
Labels: waiting for developer to respond
