Repository xbmc/repo-scripts, pull requests merged in 2020-02, with the labels that each got.

#1291 [service.librarywatchdog] 1.0.0
  service.librarywatchdog/LICENSE.txt
  service.librarywatchdog/addon.xml
  service.librarywatchdog/core/__init__.py
  service.librarywatchdog/core/emitters.py
  service.librarywatchdog/core/main.py
  service.librarywatchdog/core/polling.py
  service.librarywatchdog/core/polling_local.py
  service.librarywatchdog/core/polling_xbmc.py
  service.librarywatchdog/core/settings.py
  service.librarywatchdog/core/utils.py
  service.librarywatchdog/core/videolibrary.py
  service.librarywatchdog/icon.png
  service.librarywatchdog/resources/language/resource.language.en_gb/strings.po
  service.librarywatchdog/resources/settings.xml
  service.librarywatchdog/script.py
  service.librarywatchdog/service.py
Labels: Python3

#1312 [script.sharetv] broken
  script.sharethetv/addon.xml
Labels: Broken-Addon

#1308 [script.artistslideshow] 3.2.0
  script.artistslideshow/addon.xml
  script.artistslideshow/default.py
  script.artistslideshow/resources/language/resource.language.en_gb/strings.po
  script.artistslideshow/resources/lib/artistslideshow.py
  script.artistslideshow/resources/plugins/fanarttv.py
  script.artistslideshow/resources/plugins/lastfm.py
  script.artistslideshow/resources/plugins/theaudiodb.py
  script.artistslideshow/resources/settings.xml
Labels: Don't Merge

#1302 [script.common.plugin.cache] 2.6.1.1
  script.common.plugin.cache/LICENSES/GPL-3.0-only.txt
  script.common.plugin.cache/addon.xml
  script.common.plugin.cache/icon.png
  script.common.plugin.cache/resources/language/resource.language.en_gb/strings.po
  script.common.plugin.cache/resources/lib/__init__.py
  script.common.plugin.cache/resources/lib/entry_point.py
  script.common.plugin.cache/resources/lib/service.py
  script.common.plugin.cache/resources/lib/storage_server/StorageServer.py
  script.common.plugin.cache/resources/lib/storage_server/__init__.py
  script.common.plugin.cache/resources/lib/storage_server/storageserverdummy.py
  script.common.plugin.cache/resources/settings.xml
Labels: Python3

#1305 [script.module.python.twitch] 2.0.11.1
  script.module.python.twitch/LICENSES/GPL-3.0-only
  script.module.python.twitch/addon.xml
  script.module.python.twitch/icon.png
  script.module.python.twitch/resources/__init__.py
  script.module.python.twitch/resources/lib/__init__.py
  script.module.python.twitch/resources/lib/twitch/__init__.py
  script.module.python.twitch/resources/lib/twitch/api/__init__.py
  script.module.python.twitch/resources/lib/twitch/api/helix/__init__.py
  script.module.python.twitch/resources/lib/twitch/api/helix/analytics.py
  script.module.python.twitch/resources/lib/twitch/api/helix/bits.py
  script.module.python.twitch/resources/lib/twitch/api/helix/clips.py
  script.module.python.twitch/resources/lib/twitch/api/helix/entitlements.py
  script.module.python.twitch/resources/lib/twitch/api/helix/games.py
  script.module.python.twitch/resources/lib/twitch/api/helix/streams.py
  script.module.python.twitch/resources/lib/twitch/api/helix/subscriptions.py
  script.module.python.twitch/resources/lib/twitch/api/helix/tags.py
  script.module.python.twitch/resources/lib/twitch/api/helix/users.py
  script.module.python.twitch/resources/lib/twitch/api/helix/videos.py
  script.module.python.twitch/resources/lib/twitch/api/helix/webhooks.py
  script.module.python.twitch/resources/lib/twitch/api/parameters.py
  script.module.python.twitch/resources/lib/twitch/api/usher.py
  script.module.python.twitch/resources/lib/twitch/api/v5/__init__.py
  script.module.python.twitch/resources/lib/twitch/api/v5/bits.py
  script.module.python.twitch/resources/lib/twitch/api/v5/channel_feed.py
  script.module.python.twitch/resources/lib/twitch/api/v5/channels.py
  script.module.python.twitch/resources/lib/twitch/api/v5/chat.py
  script.module.python.twitch/resources/lib/twitch/api/v5/clips.py
  script.module.python.twitch/resources/lib/twitch/api/v5/collections.py
  script.module.python.twitch/resources/lib/twitch/api/v5/communities.py
  script.module.python.twitch/resources/lib/twitch/api/v5/games.py
  script.module.python.twitch/resources/lib/twitch/api/v5/ingests.py
  script.module.python.twitch/resources/lib/twitch/api/v5/root.py
  script.module.python.twitch/resources/lib/twitch/api/v5/search.py
  script.module.python.twitch/resources/lib/twitch/api/v5/streams.py
  script.module.python.twitch/resources/lib/twitch/api/v5/teams.py
  script.module.python.twitch/resources/lib/twitch/api/v5/users.py
  script.module.python.twitch/resources/lib/twitch/api/v5/videos.py
  script.module.python.twitch/resources/lib/twitch/exceptions.py
  script.module.python.twitch/resources/lib/twitch/keys.py
  script.module.python.twitch/resources/lib/twitch/log.py
  script.module.python.twitch/resources/lib/twitch/methods.py
  script.module.python.twitch/resources/lib/twitch/oauth/__init__.py
  script.module.python.twitch/resources/lib/twitch/oauth/clients.py
  script.module.python.twitch/resources/lib/twitch/oauth/helix/__init__.py
  script.module.python.twitch/resources/lib/twitch/oauth/helix/scopes.py
  script.module.python.twitch/resources/lib/twitch/oauth/v5/__init__.py
  script.module.python.twitch/resources/lib/twitch/oauth/v5/scopes.py
  script.module.python.twitch/resources/lib/twitch/parser.py
  script.module.python.twitch/resources/lib/twitch/queries.py
  script.module.python.twitch/resources/lib/twitch/scraper.py
Labels: Python3

#1286 [Matrix] set xbmc.python to 3.0.0
  targets.cfg
Labels: Python3
