Repository xbmc/repo-scripts, pull requests merged in 2021-06, with the labels that each got.

#2031 [script.module.inputstreamhelper@krypton] 0.5.5
  script.module.inputstreamhelper/README.md
  script.module.inputstreamhelper/addon.xml
  script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py
  script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
Labels: Merge after repo sync

#2029 [weather.ozweather@matrix] 2.0.0
  weather.ozweather/README.md
  weather.ozweather/addon.xml
  weather.ozweather/changelog.txt
  weather.ozweather/resources/banner.png
  weather.ozweather/resources/language/resource.language.en_gb/strings.po
  weather.ozweather/resources/lib/abc/__init__.py
  weather.ozweather/resources/lib/abc/abc_video.py
  weather.ozweather/resources/lib/bom.py
  weather.ozweather/resources/lib/bom/__init__.py
  weather.ozweather/resources/lib/bom/bom_forecast.py
  weather.ozweather/resources/lib/bom/bom_location.py
  weather.ozweather/resources/lib/bom/bom_radar.py
  weather.ozweather/resources/lib/bom/bom_radar_scrape_latest.py
  weather.ozweather/resources/lib/common.py
  weather.ozweather/resources/lib/forecast.py
  weather.ozweather/resources/lib/locations.py
  weather.ozweather/resources/lib/ozweather.py
  weather.ozweather/resources/lib/store.py
  weather.ozweather/resources/lib/weatherzone.py
  weather.ozweather/resources/lib/weatherzone/__init__.py
  weather.ozweather/resources/lib/weatherzone/weatherzone_forecast.py
  weather.ozweather/resources/lib/weatherzone/weatherzone_location.py
  weather.ozweather/resources/settings.xml
Labels: Approved

#2041 [script.service.next-episode@matrix] 1.2.4+matrix.1
  script.service.next-episode/addon.xml
  script.service.next-episode/libs/addon.py
  script.service.next-episode/libs/exception_logger.py
  script.service.next-episode/main.py
  script.service.next-episode/service.py
Labels: waiting for secondary review

#2051 [script.module.inputstreamhelper@krypton] 0.5.6
  script.module.inputstreamhelper/README.md
  script.module.inputstreamhelper/addon.xml
  script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py
  script.module.inputstreamhelper/lib/inputstreamhelper/config.py
  script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py
  script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py
  script.module.inputstreamhelper/resources/language/resource.language.en_gb/strings.po
  script.module.inputstreamhelper/resources/settings.xml
Labels: Merge after repo sync

#2040 [script.service.next-episode@krypton] 1.2.4
  script.service.next-episode/addon.xml
  script.service.next-episode/libs/addon.py
  script.service.next-episode/libs/exception_logger.py
  script.service.next-episode/main.py
  script.service.next-episode/service.py
Labels: waiting for secondary review
