Repository xbmc/repo-scripts, pull requests merged in 2021-03, with the labels that each got.

#1899 [script.commands] 1.1.0
  script.commands/LICENSE.txt
  script.commands/README.md
  script.commands/addon.xml
  script.commands/changelog.txt
  script.commands/commands.list
  script.commands/default.py
  script.commands/icon.png
  script.commands/resources/language/resource.language.de_de/strings.po
  script.commands/resources/language/resource.language.en_gb/strings.po
Labels: Don't Merge

#1890 [script.myepisodes] 3.0.0
  script.myepisodes/LICENSE.txt
  script.myepisodes/addon.xml
  script.myepisodes/changelog.txt
  script.myepisodes/default.py
  script.myepisodes/icon.png
  script.myepisodes/kodilogging.py
  script.myepisodes/myepisodes.py
  script.myepisodes/resources/language/resource.language.en_gb/strings.po
  script.myepisodes/resources/language/resource.language.es_es/strings.po
  script.myepisodes/resources/language/resource.language.fr_fr/strings.po
  script.myepisodes/resources/language/resource.language.it_it/strings.po
  script.myepisodes/resources/language/resource.language.pt_br/strings.po
  script.myepisodes/resources/settings.xml
  script.myepisodes/utils.py
Labels: waiting for developer to respond

#1901 [script.module.codequick] 1.0.2
  script.module.codequick/addon.xml
  script.module.codequick/lib/codequick/route.py
  script.module.codequick/lib/urlquick.py
Labels: Merge after repo sync

#1921 [service.subtitles.rvm.addic7ed@krypton] 3.1.5
  service.subtitles.rvm.addic7ed/addic7ed/actions.py
  service.subtitles.rvm.addic7ed/addon.xml
  service.subtitles.rvm.addic7ed/main.py
Labels: Merge after repo sync

#1919 [script.tvmaze.scrobbler@leia] 1.1.1
  script.tvmaze.scrobbler/addon.xml
  script.tvmaze.scrobbler/libs/exception_logger.py
  script.tvmaze.scrobbler/libs/medialibrary_api.py
  script.tvmaze.scrobbler/libs/pulled_episodes_db.py
  script.tvmaze.scrobbler/libs/scrobbling_service.py
  script.tvmaze.scrobbler/libs/tvmaze_api.py
Labels: Merge after repo sync

#1904 [service.subtitles.napiprojekt] 2.0.0
  service.subtitles.napiprojekt/LICENSE.txt
  service.subtitles.napiprojekt/README.md
  service.subtitles.napiprojekt/__init__.py
  service.subtitles.napiprojekt/addon.xml
  service.subtitles.napiprojekt/icon.png
  service.subtitles.napiprojekt/logo.png
  service.subtitles.napiprojekt/resources/language/resource.language.en_gb/strings.po
  service.subtitles.napiprojekt/resources/language/resource.language.en_us/strings.po
  service.subtitles.napiprojekt/resources/language/resource.language.pl_pl/strings.po
  service.subtitles.napiprojekt/resources/lib/NapiProjekt.py
  service.subtitles.napiprojekt/service.py
Labels: waiting for developer to respond
